import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SITE_CONFIG } from "@/lib/constants";
import { ThemeProvider } from "@/components/ThemeProvider";
import { SiteChrome } from "@/components/layout/SiteChrome";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: `${SITE_CONFIG.name} — Web Apps & Automation | ${SITE_CONFIG.developerName}`,
    template: `%s | ${SITE_CONFIG.name}`,
  },
  description: SITE_CONFIG.description,
  metadataBase: new URL(SITE_CONFIG.url),
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_CONFIG.url,
    siteName: `${SITE_CONFIG.name}`,
    // Image is auto-generated by src/app/opengraph-image.tsx — no need
    // to declare it explicitly. Omitting prevents broken-image fallback.
  },
  twitter: {
    card: "summary_large_image",
    creator: "@king5gates",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": ["Person", "LocalBusiness"],
    name: SITE_CONFIG.developerName,
    legalName: SITE_CONFIG.name,
    url: SITE_CONFIG.url,
    description: "Full Stack Developer & Automation Builder — Lusaka, Zambia",
    address: {
      "@type": "PostalAddress",
      addressLocality: SITE_CONFIG.location.city,
      addressCountry: SITE_CONFIG.location.countryCode,
    },
    knowsAbout: ["Web Development", "Workflow Automation", "Full Stack Development", "Next.js", "Automation Builder"],
    image: `${SITE_CONFIG.url}/opengraph-image`,
    sameAs: [SITE_CONFIG.socials.github, SITE_CONFIG.socials.twitter],
  };

  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="bg-white dark:bg-[#060608] text-gray-900 dark:text-gray-100 antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SiteChrome>{children}</SiteChrome>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
